- frontend/src/layers/CumuliDepth.ts
As noticed in https://github.com/soaringmeteo/soaringmeteo/pull/32#issuecomment-1100677508 cumulus mediocris were shown completely opaque.
This PR fixes that.
Regarding the second part of the comment:
> Would grey not be better than red for high-density clouds?
I chose to use red for highly developed clouds (congestus or cumulonimbus) because they might be dangerous for soaring. But I am open to discussion :)
> Cumulus mediocris should not be opaque

- frontend/src/diagrams/Meteogram.tsx
- frontend/src/layers/ThQ.ts
Previously, the computation was too penalized when there was a little bit of clouds.
The new computation uses a logistic function, just like it was done in soaringmeteo v1. I believe the new results are a bit better, but we experience will tell us if we need to tweak again the formula manually...
Before:
After:
Before:
After:
For reference, the “mixed” layer shows this:
> Improve XC flying potential index

- README.md
- backend/src/main/scala/org/soaringmeteo/gfs/out/Forecast.scala
- backend/src/main/scala/org/soaringmeteo/gfs/out/LocationForecasts.scala
- frontend/src/data/Forecast.ts
- frontend/src/diagrams/Meteogram.tsx
- frontend/src/layers/ThQ.ts
We need sun to get thermals. Therefore, the XC flying potential indicator was based on the cloud cover. However, we experienced that high cloud cover was degrading the value of the indicator too much.
We propose to base the XC flying potential on the thermal velocity instead of the cloud cover. The thermal velocity is computed from the boundary layer height and the heat rate, so in a sense it also contains the information about the sunshine.
Before:
After:
Note the difference around Annecy. This is because GFS tells it will be cloudy:
> Base XC flying potential on thermal velocity instead of cloud cover

- backend/src/main/scala/org/soaringmeteo/gfs/DownloadAndRead.scala
- backend/src/main/scala/org/soaringmeteo/gfs/Main.scala
- backend/src/main/scala/org/soaringmeteo/gfs/in/ForecastRun.scala
The implementation was motivated by the desire to download the GFS data once (several GB in total) and use it for both soarV2 and soarGFS. However, it didn’t work in practice because the GRIB files downloaded here are significantly larger than the ones downloaded by old soarGFS, and then old soarGFS takes too long time to analyze them and eventually fails.
In this commit, we don’t try to download the GRIB files anymore in way that they can be reused by old soarGFS. The consequence is that both soarV2 and old soarGFS will download data from the NOAA servers, so we need to be careful to not do it at the same time to avoid hitting the rate limit (120 hits/min).
> Don’t download GRIB files for old-soarGFS anymore

- frontend/src/App.tsx
- frontend/src/Burger.tsx
- frontend/src/PeriodSelector.tsx
---
I first tried to reuse the same green navigation bar as on https://soaringmeteo.org, but I found that it was eating too much space:
So, ultimately I decided to only add a “burger button” on the top left corner, as shown in the first screenshots.
> Add a menu with links to the other parts of the website

- backend/src/main/scala/org/soaringmeteo/gfs/in/Forecast.scala
- backend/src/main/scala/org/soaringmeteo/gfs/in/GfsGrib.scala
- backend/src/main/scala/org/soaringmeteo/gfs/out/Forecast.scala
- frontend/src/diagrams/Meteogram.ts
Fetch data at a few more elevation levels to get more points when drawing the meteograms or the soundings.
Unfortunately, the benefits are visible mostly for locations that are below 500 m only.
Before:
After:
Before:
After:
> Increase precision of meteograms and soundings

- frontend/src/diagrams/Sounding.tsx
- frontend/src/help/Help.tsx
I find it easier to use different colors to indicate absolutely unstable vs conditionally unstable air.
Before:
After:
> Color-code for unstable air profiles

- frontend/src/diagrams/Meteogram.ts
- frontend/src/diagrams/Sounding.tsx
- frontend/src/help/Help.tsx
- frontend/src/layers/ThermalVelocity.tsx
An alternative to #37. We add another line below the XC potential to show the estimated thermal velocity:
I am not 100% sure about this. On the one hand I would like this information to be shown somehow, but on the other hand I feel like there is maybe too much information… Maybe I could display it only if the user enabled some setting (“advanced meteograms”).
> Show thermal velocity in meteograms

- backend/src/main/scala/org/soaringmeteo/gfs/out/Forecast.scala
- backend/src/main/scala/org/soaringmeteo/gfs/out/LocationForecasts.scala
- backend/src/main/scala/org/soaringmeteo/gfs/out/Winds.scala
- frontend/src/data/Forecast.ts
- frontend/src/help/Help.tsx
- frontend/src/layers/BoundaryLayerDepth.tsx
- frontend/src/layers/Layers.tsx
- frontend/src/layers/SoaringLayerDepth.tsx
- frontend/src/layers/ThQ.tsx
- frontend/src/map/CanvasLayer.ts
In the meteograms and in the XC flying potential index, we used to overestimate the “soaring ceiling” in case of a low cloud base. Basically, we were ignoring the fact that we can’t really go higher than the cloud base (in VFR).
We fix this issue by capping the boundary layer to the cloud base, in case of the presence of cumulus clouds.
---
Before:
After (look especially at a day like the 20th of January):
---
Before:
After:
----
Before:
After:
---
Before:
After:
> Cap the boundary layer with the cloud base

- frontend/src/help/Help.tsx
I wanted to see if we could link better the explanation of the meteograms with their content by reusing the same colors. Here is how it looks like:
For reference, here is the current state:
Also, for sounding diagrams:
Before, it was as follows:
However, I am not sure about using those colors… Yellow and cyan are hard to read on a white background.
Any suggestions? Maybe I should just write them in bold without changing the color.
> Highlight better important parts of the help content

- CONTRIBUTING.md
- backend/src/main/scala/org/soaringmeteo/gfs/JsonWriter.scala
- backend/src/main/scala/org/soaringmeteo/gfs/out/package.scala
- frontend/src/data/ForecastMetadata.ts
Currently, changing the format of the forecast data produced by the server is delicate to handle: the frontend still shows the older (incompatible) forecast runs, and more importantly there is a short period of time where the frontend is not able to consume the data produced by the server.
We now indicate the version of the format of the data produced by the backend and consumed by the frontend so that whenever we need to change the format of the data produced by the backend, we can simply delay the deployment of the frontend and only when we will deploy the updated frontend then the new forecast data will be consumed (in the meantime, the frontend will still work with the older forecast data).
> Support breaking changes in the forecast data format

- frontend/src/PeriodSelector.tsx
- frontend/src/State.tsx
- frontend/src/diagrams/Sounding.tsx
- frontend/src/help/Help.tsx
Also include a button to switch from meteograms to sounding diagrams and vice versa, and a button to show the help.
Fixes #63
> Add more information to the bottom of meteograms and sounding diagrams

- frontend/src/diagrams/Diagram.ts
- frontend/src/diagrams/Meteogram.ts
- frontend/src/help/Help.tsx
- frontend/src/help/data.ts
Credits to @Boran for the idea.
> Move thunderstorm icon to the “rain diagram” and scale the icon according to the risk of thunderstorm

- frontend/package.json
- frontend/src/App.tsx
- frontend/src/LayersSelector.tsx
- frontend/src/PeriodSelector.tsx
- frontend/src/State.tsx
- frontend/src/css-hooks.ts
- frontend/src/data/ForecastMetadata.ts
- frontend/src/shared.ts
- frontend/yarn.lock
Add back the “-24” and “+24” buttons for the WRF model, and also show a date selector:
> Improve the way to select the day of forecast

- frontend/src/App.tsx
- frontend/src/Burger.tsx
- frontend/src/DetailedView.tsx
- frontend/src/LayerKeys.tsx
- frontend/src/LocationDetails.tsx
- frontend/src/PeriodSelector.tsx
- frontend/src/State.tsx
- frontend/src/data/ForecastMetadata.ts
- frontend/src/diagrams/Meteogram.tsx
- frontend/src/diagrams/Sounding.tsx
- frontend/src/help/Help.tsx
- frontend/src/layers/CumuliDepth.tsx
- frontend/src/layers/Layer.tsx
- frontend/src/layers/Rain.tsx
- frontend/src/layers/SoaringLayerDepth.tsx
- frontend/src/layers/ThQ.tsx
- frontend/src/layers/ThermalVelocity.tsx
- frontend/src/layers/Wind.tsx
- frontend/src/map/Map.ts
- frontend/src/map/Overlay.tsx
- frontend/src/styles/Styles.tsx
This is a departure from the current user interface in soarWRF and soarGFS.
Instead of opening a popup when the user clicks on the map, we show the location details in a box on the side of the window. This resolves two issues:
- since there is no popup anymore, the users are not bothered by the popup if they want to click on point close to the one previously clicked (see the videos below)
- showing the meteograms or sounding diagrams of multiple locations is simpler as the users don’t need to click to “Meteogram” again and again for each location.
I think the resulting layout is still a bit weird (not everything is correctly aligned), and I know it does not work very well on small screens. I will work on that tomorrow.
Here is a video that shows the existing behavior and another video …
> Don’t show the location details in a popup

- frontend/src/LayerKeys.tsx
- frontend/src/layers/CumuliDepth.tsx
- frontend/src/layers/Layer.tsx
Because the map overlays are a bit transparent, the colors seen in the overlay legend (bottom right of the screen) can look pretty different from those seen on the map overlays.
We apply some transparency to the colors shown in the legend as well to make them look more similar to the colors in the overlays.
Before:
After:
Also with clouds and rain. Before:
After:
> Make colors in legends look a bit more like the colors on the map

- backend/build.sbt
- backend/common/src/main/scala/org/soaringmeteo/out/VectorTiles.scala
- backend/common/src/main/scala/org/soaringmeteo/out/package.scala
- backend/project/Dependencies.scala
- frontend/src/data/ForecastMetadata.ts
- frontend/src/map/Map.ts
For soarGFS, this decreases the size of the frontend assets from 20 GB to 11 GB.
For soarWRF, this decreases the size of the assets from 3.8 GB to 2.4 GB.
Note that the size of the data downloaded by the clients does not decrease, though, because JSON used to be transferred in gzip (although it is possible to enable gzip on .mvt assets too and save some kB).
You can see the result on https://soarwrf3.soaringmeteo.org/v2
> Use the MVT format for vector tiles instead of JSON

- frontend/index.html
- frontend/src/App.tsx
- frontend/src/Burger.tsx
- frontend/src/BurgerButton.tsx
- frontend/src/LocationDetails.tsx
- frontend/src/help/Help.tsx
- frontend/src/help/HelpButton.tsx
Lazy load a couple of components to slightly reduce the number of HTTP requests and transferred data to initially load the page.
Before: 6 requests, 521 kB (172 kB compressed)
After: 5 requests, 495 kB (155 kB compressed)
> Minor optimizations on the bundle

- frontend/index.html
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/Plausible.tsx
- frontend/src/State.tsx
- frontend/src/map/Map.ts
- frontend/yarn.lock
Since the app uses the same URL `/v2` we can not monitor in the stats whether our users use the new interface to see the WRF results or the GFS results.
To address this issue, we replace the standard analytics script with a custom one that attaches a custom property to every “page view” event to indicate the underlying model (GFS or WRF).
As a consequence, we can now segment visits according to that property:
Alternatively, we could rewrite the URL to use distinct URLs such as `/v2/gfs` and `/v2/wrf` but I believe custom properties attached to the page view events are a cleaner way to track that information.
> Collect stats about the numerical weather prediction model used by our visitors

- frontend/src/PeriodSelector.tsx
- frontend/src/styles/Styles.tsx
I find it difficult to use on mobile.
Before -> After:
> Slightly increase the size of the buttons to select the date and time of the forecast

- frontend/messages/de.json
- frontend/messages/en.json
- frontend/messages/es.json
- frontend/messages/fr.json
- frontend/messages/it.json
- frontend/messages/pl.json
- frontend/messages/pt.json
- frontend/messages/sk.json
- frontend/src/LayerKeys.tsx
- frontend/src/Settings.tsx
- frontend/src/State.tsx
- frontend/src/styles/Forms.tsx
Add a new setting allowing the users to hide the map key. This feature was requested on the “Soaringemeteo v2 feedback” channel.
> Support hiding the map key
